#### Basics

In [20]:
import numpy as np

In [19]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
a.ndim

1

In [11]:
b.ndim

2

In [21]:
a.shape

(3,)

In [22]:
b.shape

(2, 3)

In [23]:
a.dtype

dtype('int32')

In [24]:
b.dtype

dtype('float64')

In [25]:
a.itemsize

4

In [27]:
a.size

3

In [29]:
a.nbytes

12

In [26]:
b.itemsize

8

In [28]:
b.size

6

In [30]:
b.nbytes

48