### Accessing/Changing specific elements, rows, columns, etc

In [2]:
import numpy as np

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
a.shape

(2, 7)

In [11]:
a[1, 5]

np.int64(13)

In [12]:
a[1, -3]

np.int64(12)

In [8]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
a[:, 2]

array([ 3, 10])

In [15]:
a[0, 1:-1: 2]

array([2, 4, 6])

In [16]:
a[0, 1:6:2]

array([2, 4, 6])

In [17]:
a[0, 1:-2:2]

array([2, 4])

In [19]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


##### 3-D Array

In [30]:
b = np.array([
[[1,2],[3,4]],
[[5,6],[7,8]]
])

In [32]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
print(b[0])

[[1 2]
 [3 4]]


In [ ]:
#Get specific element (work outside in)

In [34]:
b[0,1,1]

np.int64(4)

In [35]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [26]:
b[:,1,:] = [[9,9],[8,8]]

In [36]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.