### Initializing Different Types of Arrays

In [1]:
import numpy as np

In [4]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [9]:
#Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [15]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [16]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
a.shape

(2, 7)

In [13]:
#Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [18]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [19]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.27715005, 0.26898792],
       [0.88739178, 0.09685475],
       [0.41065252, 0.39356864],
       [0.25261951, 0.68791609]])

In [20]:
np.random.rand(4,2,3)

array([[[0.86985159, 0.20266193, 0.17575111],
        [0.93272468, 0.02866549, 0.26033156]],

       [[0.98473537, 0.94271539, 0.60923256],
        [0.58891477, 0.80235292, 0.25523655]],

       [[0.28857175, 0.57981339, 0.07316595],
        [0.0868873 , 0.27325901, 0.72538712]],

       [[0.00415658, 0.27038966, 0.47164051],
        [0.45830055, 0.05717153, 0.4454508 ]]])

In [21]:
np.random.random_sample(a.shape)

array([[0.39679   , 0.00869416, 0.14455731, 0.40825018, 0.67255947,
        0.5172214 , 0.03951619],
       [0.50315184, 0.47240131, 0.68173041, 0.29612939, 0.48996568,
        0.8789888 , 0.83624788]])

In [22]:
#Random Integer values
np.random.randint(7, size=(3,3))

array([[0, 4, 6],
       [5, 3, 3],
       [5, 1, 4]], dtype=int32)

In [23]:
np.random.randint(-4,8, size=(3,3))

array([[-3,  0, -4],
       [ 2,  5, -2],
       [ 4, -1, -1]], dtype=int32)

In [24]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
#Repeat an array
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [36]:
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [37]:
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [38]:
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [39]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [42]:
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [45]:
b = a.copy()
b

array([1, 2, 3])

In [46]:
b[0] = 100
b

array([100,   2,   3])

In [47]:
a

array([1, 2, 3])