### Mathematics

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
a ** 2

array([ 1,  4,  9, 16])

In [11]:
a

array([1, 2, 3, 4])

In [12]:
b = np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [13]:
a + b

array([2, 2, 4, 4])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])