### Linear Algebra

In [1]:
import numpy as np

In [2]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
b = np.full((3,2), 2)
print(b)


[[2 2]
 [2 2]
 [2 2]]


In [4]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [5]:
# Find the determinant
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.linalg.det(c)

np.float64(1.0)