### Statistics

In [1]:
import numpy as np

In [3]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.min(stats)

np.int64(1)

In [5]:
np.max(stats)

np.int64(6)

In [6]:
np.min(stats, axis=0)

array([1, 2, 3])

In [7]:
np.min(stats, axis=1)

array([1, 4])

In [8]:
np.max(stats, axis=0)

array([4, 5, 6])

In [9]:
np.max(stats, axis=1)

array([3, 6])

In [10]:
np.sum(stats, axis=0) 

array([5, 7, 9])

In [11]:
np.sum(stats, axis=1)

array([ 6, 15])