### Reorganizing Arrays

In [2]:
import numpy as np

In [3]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
after = before.reshape((4, 2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
after = before.reshape((2, 4))
after

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
after = before.reshape((8, 1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [7]:
after = before.reshape((1, 8))
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [8]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [10]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])


In [11]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [14]:
#Horizontal stack
h1 = np.ones((2,4))
print(h1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
h2 = np.zeros((2,2))
print(h2)

[[0. 0.]
 [0. 0.]]


In [16]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])